dubbo:
     uc0001: IUserCenterService
     uc0002: IUserCenterService
     uc0003: IUserCenterService
     uc0004: IUserCenterService
     uc0005: IUserCenterService
     uc0006: IUserCenterService
     uc0007: IUserCenterService
     uc0008: IUserCenterService
     uc0009: IUserCenterService
     uc0010: IUserCenterService
     uc0011: IUserCenterService
     uc0012: IUserCenterService
     bs0001: IMessageService
     bs0002: IMessageService
     bs0003: IMessageService
     bs0004: IMessageService
     bs0005: IMessageService
     bs0006: IMessageService
     bs0016: IMessageService
     pd0001: IProductService
     st0001: ISettleService
     cs0001: ICashierService
     cs0002: ICashierService
     cs0003: ICashierService
     cs0004: ICashierService
     pff0001: IBillOpeService
     pff0002: IBillOpeService
